# Generated by Django 3.0.5 on 2020-05-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0020_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphMem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('no_of_tasks', models.IntegerField(default=0)),
                ('GraphMemid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BucketList.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
