# Generated by Django 3.0.5 on 2020-05-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0021_auto_20200516_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphmem',
            name='month',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
