# Generated by Django 3.0.5 on 2020-05-16 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BucketList', '0022_auto_20200516_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphmem',
            name='GraphMemid',
        ),
        migrations.RemoveField(
            model_name='graphmem',
            name='month',
        ),
        migrations.RemoveField(
            model_name='graphmem',
            name='no_of_tasks',
        ),
        migrations.AddField(
            model_name='graphmem',
            name='memid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graphmem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='No_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_jan', models.IntegerField(default=0)),
                ('task_feb', models.IntegerField(default=0)),
                ('task_mar', models.IntegerField(default=0)),
                ('task_apr', models.IntegerField(default=0)),
                ('task_june', models.IntegerField(default=0)),
                ('task_july', models.IntegerField(default=0)),
                ('task_aug', models.IntegerField(default=0)),
                ('task_sept', models.IntegerField(default=0)),
                ('task_oct', models.IntegerField(default=0)),
                ('task_may', models.IntegerField(default=0)),
                ('task_nov', models.IntegerField(default=0)),
                ('task_dec', models.IntegerField(default=0)),
                ('taskid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BucketList.GraphMem')),
            ],
        ),
    ]
