# Generated by Django 3.0.5 on 2020-05-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0023_auto_20200516_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphmem',
            name='task_apr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphmem',
            name='task_aug',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphmem',
            name='task_dec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphmem',
            name='task_feb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphmem',
            name='task_jan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphmem',
            name='task_july',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphmem',
            name='task_june',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphmem',
            name='task_mar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphmem',
            name='task_may',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphmem',
            name='task_nov',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphmem',
            name='task_oct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphmem',
            name='task_sept',
            field=models.IntegerField(default=0),
        ),
    ]
