# Generated by Django 3.0.5 on 2020-05-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0024_auto_20200517_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphmem',
            name='task_apr',
        ),
        migrations.RemoveField(
            model_name='graphmem',
            name='task_aug',
        ),
        migrations.RemoveField(
            model_name='graphmem',
            name='task_dec',
        ),
        migrations.RemoveField(
            model_name='graphmem',
            name='task_feb',
        ),
        migrations.RemoveField(
            model_name='graphmem',
            name='task_jan',
        ),
        migrations.RemoveField(
            model_name='graphmem',
            name='task_july',
        ),
        migrations.RemoveField(
            model_name='graphmem',
            name='task_june',
        ),
        migrations.RemoveField(
            model_name='graphmem',
            name='task_mar',
        ),
        migrations.RemoveField(
            model_name='graphmem',
            name='task_may',
        ),
        migrations.RemoveField(
            model_name='graphmem',
            name='task_nov',
        ),
        migrations.RemoveField(
            model_name='graphmem',
            name='task_oct',
        ),
        migrations.RemoveField(
            model_name='graphmem',
            name='task_sept',
        ),
    ]
