# Generated by Django 3.0.5 on 2020-05-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0025_auto_20200517_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='leader_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
