# Generated by Django 3.0.5 on 2020-05-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0026_auto_20200517_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='leader_pin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
