# Generated by Django 3.0.5 on 2020-05-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0031_auto_20200519_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='memberpin',
            field=models.TextField(blank=True, max_length=4, null=True),
        ),
    ]
